version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "22:00"
    labels: [ github_actions ]

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      time: "22:00"
    labels: [ dependencies ]
    ignore:
      - dependency-name: self.*