-keep,allowoptimization,allowobfuscation public class * extends com.android.internal.app.IAppOpsCallback$Stub { public <methods>; }
-keep,allowoptimization,allowobfuscation public class * extends android.content.pm.IPackageInstallerCallback$Stub { public <methods>; }
-keep,allowoptimization,allowobfuscation public class * extends android.content.IIntentSender$Stub { public <methods>; }